version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: payout_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: payout_user
      POSTGRES_PASSWORD: payout_pass
      POSTGRES_DB: payout_db
    ports:
      - "5433:5432"
    volumes:
      - payout_pg_data:/var/lib/postgresql/data

volumes:
  payout_pg_data: